#!/bin/bash
MAIN_CXX=scaleup
cccmp="g++ $MAIN_CXX.cc -o $MAIN_CXX -I./ -std=c++20 -DDEBUG_MAT -D__STATIC_DECLAIR -Wall"
echo $cccmp && $($cccmp)
[ ! -e $1 ] && [ "$1" == "-r" ] && echo "running $MAIN_CXX" && eval ./$MAIN_CXX
