#!/bin/bash
MATCHSTR=$(echo -e "1\n1\n1\n0\n1")
COLOR() {
	echo "\033[1;3$1m"	
}
END="\033[00m"
COUNTER=$1;

run() {
	CNT=1;REF=0;
	RESULT=$(eval ./a.out)
	for n in $MATCHSTR 
	do 
		[ ! -e  $(awk 'BEGIN{RS=" ";ORS="\n"}{print}' <<< $RESULT | awk "NR==$CNT{if(\$1 == $n ) print \"t\"}") ] && REF=$(($REF+1))
		CNT=$(($CNT+1))
	done
	if [ $REF -eq $(($(awk '{print NR}' <<< $MATCHSTR | tail -1))) ]; then
		echo -e "$(COLOR 3)*$END"$(COLOR 2) test case $(COLOR 7)$1$END $(COLOR 2)has succ $END
	else
		echo -e "$(COLOR 3)*$END"$(COLOR 5) test case $(COLOR 7)$1$END $(COLOR 5)has failed $END
	fi
}
[ -z $1 ] && echo "help: n (n == number of times to run)" && exit
i=0;while [ $COUNTER -gt 0 ]; do run $i;COUNTER=$(($COUNTER-1));i=$(($i+1));done
